import { LOCATION, RESOURCE_GROUP, VNET_NAME } from './common';

/* Virtual Network (VNet) configuration parameters */
export const azureVnetResourcesparams = {
  resourceGroupName: RESOURCE_GROUP,
  location: LOCATION,
  vnetName: VNET_NAME,
  vnetAddressSpace: "10.2.0.0/16",
  vnetTags: {
    Project: "MultiCloud",
  },
  subnets: [
    {
      name: "subnet1",
      cidr: "10.2.10.0/24",
    },
    {
      name: "subnet2",
      cidr: "10.2.20.0/24",
    },
  ],
  natenabled: false,
  bastionenabled: false,
  bastionSubnetcidr: "10.2.110.0/24",
  nsgTags: {
    Purpose: "VnetSecurity",
  },
  nsgRules: [
    {
      name: "AllowVnetInBound",
      priority: 100,
      direction: "Inbound",
      access: "Allow",
      protocol: "*",
      sourcePortRange: "*",
      destinationPortRange: "*",
      sourceAddressPrefix: "VirtualNetwork",
      destinationAddressPrefix: "VirtualNetwork",
    },
    {
      name: "AllowAzureLoadBalancerInBound",
      priority: 101,
      direction: "Inbound",
      access: "Allow",
      protocol: "*",
      sourcePortRange: "*",
      destinationPortRange: "*",
      sourceAddressPrefix: "AzureLoadBalancer",
      destinationAddressPrefix: "*",
    },
    {
      name: "allow-ssh-from-bastion",
      priority: 102,
      direction: "Inbound",
      access: "Allow",
      protocol: "Tcp",
      sourcePortRange: "22",
      destinationPortRange: "22",
      sourceAddressPrefix: "10.2.110.0/24",
      destinationAddressPrefix: "*",
    },
    {
      name: "DenyAllInBound",
      priority: 4096,
      direction: "Inbound",
      access: "Deny",
      protocol: "*",
      sourcePortRange: "*",
      destinationPortRange: "*",
      sourceAddressPrefix: "*",
      destinationAddressPrefix: "*",
    },
    {
      name: "AllowVnetOutBound",
      priority: 100,
      direction: "Outbound",
      access: "Allow",
      protocol: "*",
      sourcePortRange: "*",
      destinationPortRange: "*",
      sourceAddressPrefix: "VirtualNetwork",
      destinationAddressPrefix: "VirtualNetwork",
    },
    {
      name: "AllowWebTrafficOutBound",
      priority: 101,
      direction: "Outbound",
      access: "Allow",
      protocol: "*",
      sourcePortRange: "*",
      destinationPortRange: "*",
      sourceAddressPrefix: "VirtualNetwork",
      destinationAddressPrefix: "Internet",
    },
    {
      name: "AllowAllOutBound",
      priority: 4095,
      direction: "Outbound",
      access: "Allow",
      protocol: "*",
      sourcePortRange: "*",
      destinationPortRange: "*",
      sourceAddressPrefix: "*",
      destinationAddressPrefix: "*",
    },
    {
      name: "DenyAllOutBound",
      priority: 4096,
      direction: "Outbound",
      access: "Deny",
      protocol: "*",
      sourcePortRange: "*",
      destinationPortRange: "*",
      sourceAddressPrefix: "*",
      destinationAddressPrefix: "*",
    },
  ],
};