export const nsgTags = {
    Purpose: "VnetSecurity",
};

export const nsgRules = [
    {
        name: "AllowVnetInBound",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
    },
    {
        name: "AllowAzureLoadBalancerInBound",
        priority: 101,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "AzureLoadBalancer",
        destinationAddressPrefix: "*",
    },
    {
        name: "allow-ssh-from-bastion",
        priority: 102,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "22",
        destinationPortRange: "22",
        sourceAddressPrefix: "10.2.110.0/24",
        destinationAddressPrefix: "*",
    },
    {
        name: "DenyAllInBound",
        priority: 4096,
        direction: "Inbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
    },
    {
        name: "AllowVnetOutBound",
        priority: 100,
        direction: "Outbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
    },
    {
        name: "AllowWebTrafficOutBound",
        priority: 101,
        direction: "Outbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "Internet",
    },
    {
        name: "AllowAllOutBound",
        priority: 4095,
        direction: "Outbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
    },
    {
        name: "DenyAllOutBound",
        priority: 4096,
        direction: "Outbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
    },
];